#!/bin/bash
# Prefix commit message with ticket id
#

COMMIT_MSG_FILE=$1
COMMIT_MESSAGE=$(cat $COMMIT_MSG_FILE)

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
TICKET_ID=$(echo $BRANCH_NAME | sed -nr 's,([a-z-]+/)?([A-Z]+-[0-9]+)(-|_).+,\2,p')

# If no ticket is extracted from the branch name or the commit message already
# contains the prefix (`--amend`), then do not add it again.
if [[ "$TICKET_ID" == "" || "$COMMIT_MESSAGE" == "$TICKET_ID"* ]]; then
  exit 0
fi

echo "$TICKET_ID: $COMMIT_MESSAGE" > $COMMIT_MSG_FILE
