##############################################################
##                      Miscellaneous                       ##
##############################################################
# Set "**" to match all files and zero or more (sub)directories
shopt -s globstar

# Make Bash append rather than overwrite the history on disk
shopt -s histappend

# Whenever displaying the prompt, write the previous line to disk
export PROMPT_COMMAND="history -a;$PROMPT_COMMAND"

##############################################################
##                   Internal Variables                     ##
##############################################################
# Path to code directory
CODE_DIR="$HOME/code"

##############################################################
##                     Bash Completions                     ##
##############################################################
# Complete $CODE_DIR directory entries
__code_complete() {
  local cur=$(join_by / "${COMP_WORDS[@]}" | sed -e 's/code\///')
  COMPREPLY=( $(compgen -d "$CODE_DIR/$cur" | sed -e 's,'".*/"',,'))
}

complete -F __code_complete code

# alias completion definition function
function make_completion_wrapper () {
  local function_name="$2"
  local arg_count=$(($#-3))
  local comp_function_name="$1"
  shift 2
  local function="
    function $function_name {
      ((COMP_CWORD+=$arg_count))
      COMP_WORDS=( "$@" \${COMP_WORDS[@]:1} )
      "$comp_function_name"
      return 0
    }"
  eval "$function"
  echo $function_name
  echo "$function"
}

# convenience function to auto-name the wrapper generated by make-completion-wrapper
function complete_alias  {
    # uses make-completion-wrapper: https://unix.stackexchange.com/a/4220/50978
    # example usage
    # complete-alias _pass pshow pass show
    # complete-alias _pass pgen pass generate

    EXISTING_COMPLETION_FN=${1} && shift
    ALIAS=${1} && shift
    AUTOGEN_COMPLETION_FN="__autogen_completion_${ALIAS}"
    make_completion_wrapper ${EXISTING_COMPLETION_FN} ${AUTOGEN_COMPLETION_FN} ${*}
    complete -F ${AUTOGEN_COMPLETION_FN} ${ALIAS}
}

##############################################################
##                        Functions                         ##
##############################################################
# Used internally in bash completion functions
function join_by()      { local IFS="$1"; shift; echo "$*" ; }

# Go to code/<subdirectory>
function code()         { cd "$CODE_DIR/$(join_by / "$@")" ; }

# RPM extraction
function xrpm()         { rpm2cpio "$1" | cpio -idmv       ; }

# Remove duplicated entries in PATH
function sanitize_path() {
  if [ -n "$PATH" ]; then
    old_PATH=$PATH:; PATH=
    while [ -n "$old_PATH" ]; do
      x=${old_PATH%%:*}     # the first remaining entry
      case $PATH: in
        *:"$x":*) ;;        # already there
        *) PATH=$PATH:$x;;  # not there yet
      esac
      old_PATH=${old_PATH#*:}
    done
    PATH=${PATH#:}
    unset old_PATH x
  fi
}
